# Generated by Django 5.0.2 on 2024-02-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "place_of_death",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "place_of_birth_original_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "place_of_death_original_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default=("M", "Male"),
                        max_length=1,
                    ),
                ),
                (
                    "pseudonym_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pseudonyms",
                        to="web.person",
                    ),
                ),
            ],
        ),
    ]
