# Generated by Django 5.0.2 on 2024-02-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_order", models.PositiveIntegerField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="web.person",
                    ),
                ),
            ],
            options={
                "ordering": ["author_order"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="books", through="web.Authorship", to="web.person"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="authorship",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorships",
                to="web.book",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="authorship",
            unique_together={("person", "book", "author_order")},
        ),
    ]
