# Generated by Django 5.0.2 on 2024-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_book_author_of_motto_book_author_xml_book_dedication_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
