# Generated by Django 5.0.2 on 2024-02-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_book_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="edition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
