# Generated by Django 5.0.2 on 2024-03-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_person_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="text_search",
            field=models.TextField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="authorship",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authorships",
                to="web.book",
            ),
        ),
        migrations.AlterField(
            model_name="authorship",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authorships",
                to="web.person",
            ),
        ),
    ]
