# Generated by Django 5.0.2 on 2024-03-15 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_book_content_book_text_book_text_search_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(null=True)),
                ("original_id", models.PositiveIntegerField(null=True)),
                ("order_in_book", models.PositiveIntegerField()),
                ("text", models.TextField(null=True)),
                (
                    "text_search",
                    models.TextField(db_index=True, editable=False, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web.person",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poems",
                        to="web.book",
                    ),
                ),
            ],
        ),
    ]
