# Generated by Django 5.0.2 on 2024-03-15 12:08

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_poem"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="text_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="text_search",
            field=models.TextField(editable=False, null=True),
        ),
    ]
