# Generated by Django 5.0.2 on 2024-03-27 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_book_text_search_vector_alter_book_text_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoemOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "poem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="day",
                        to="web.poem",
                    ),
                ),
            ],
        ),
    ]
