# Generated by Django 5.0.2 on 2024-04-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0012_book_public_domain_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="next_issue_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="previous_issues",
                to="web.poem",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="public_domain_year",
            field=models.IntegerField(
                blank=True,
                help_text="Year when the book enters the public domain, based on the author's death year + 71 years.",
                null=True,
                verbose_name="Public Domain Start Year",
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="poems",
                to="web.person",
            ),
        ),
    ]
