# Generated by Django 5.0.2 on 2024-04-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0013_poem_next_issue_of_alter_book_public_domain_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoemInCCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ccv_id", models.CharField(max_length=24)),
                ("ccv_title", models.TextField(null=True)),
                ("ccv_author", models.CharField(max_length=225, null=True)),
                ("ccv_year", models.IntegerField(blank=True, null=True)),
                ("ccv_part_order", models.IntegerField(blank=True, null=True)),
                (
                    "book_in_cek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poems_in_ccv",
                        to="web.book",
                    ),
                ),
                (
                    "ccv_next_issue_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_issues_in_ccv",
                        to="web.poem",
                    ),
                ),
                (
                    "ccv_part_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts_in_ccv",
                        to="web.poem",
                    ),
                ),
                (
                    "poem_in_cek",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="poems_in_ccv",
                        to="web.poem",
                    ),
                ),
            ],
        ),
    ]
