# Generated by Django 5.0.2 on 2024-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0014_poeminccv"),
    ]

    operations = [
        migrations.AddField(
            model_name="poeminccv",
            name="cluster_id",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
