# Generated by Django 5.0.2 on 2024-04-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_poeminccv_cluster_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="poeminccv",
            name="cek_next_issue_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_issues_in_ccv",
                to="web.poem",
            ),
        ),
        migrations.AddField(
            model_name="poeminccv",
            name="cek_part_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parts_in_ccv",
                to="web.poem",
            ),
        ),
        migrations.AlterField(
            model_name="poeminccv",
            name="ccv_next_issue_of",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="poeminccv",
            name="ccv_part_of",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
