# Generated by Django 5.0.2 on 2024-05-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_poeminccv_cek_next_issue_of_poeminccv_cek_part_of_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="versology_stats",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poem",
            name="versology_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
