# Generated by Django 5.0.2 on 2024-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0018_clustering_cluster_poemincluster"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="for_schools",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="for_schools",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="poem",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
