# Generated by Django 5.0.2 on 2024-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0022_rename_description_person_side_note_book_side_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="pdf_file1",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file1_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
