# Generated by Django 5.0.2 on 2024-09-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0023_person_pdf_file1_person_pdf_file1_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="pdf_file1_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
