# Generated by Django 5.0.2 on 2024-10-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0024_alter_person_pdf_file1_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pdf_file1",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file1_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file2",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file2_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file3",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file3_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file4",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file4_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file5",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="book",
            name="pdf_file5_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file2",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file2_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file3",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file3_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file4",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file4_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file5",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="person",
            name="pdf_file5_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
