# Generated by Django 5.0.2 on 2025-02-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0025_book_pdf_file1_book_pdf_file1_title_book_pdf_file2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoemAIText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "poem",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_text",
                        to="web.poem",
                    ),
                ),
            ],
        ),
    ]
