# Generated by Django 5.0.2 on 2025-02-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0026_poemaitext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lemma", models.CharField(blank=True, default="", max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("person", "Person"), ("place", "Place")],
                        max_length=10,
                    ),
                ),
                ("wiki_id", models.CharField(blank=True, default="", max_length=50)),
                ("to_index", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EntityOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_id", models.CharField(max_length=20)),
                ("length", models.PositiveSmallIntegerField()),
                ("tokens", models.TextField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="web.entity",
                    ),
                ),
                (
                    "poem_ai_text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_occurrences",
                        to="web.poemaitext",
                    ),
                ),
            ],
        ),
    ]
