# Generated by Django 5.0.2 on 2025-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0027_entity_entityoccurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="lemma_en",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="entity",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="entity",
            name="summary_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="entity",
            name="wiki_link",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="entity",
            name="wiki_link_en",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
