# Generated by Django 5.0.2 on 2025-02-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0028_entity_lemma_en_entity_summary_entity_summary_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="lemma",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="lemma_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="summary",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="summary_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="wiki_id",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="wiki_link",
            field=models.URLField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="wiki_link_en",
            field=models.URLField(blank=True, default="", max_length=500, null=True),
        ),
    ]
