# Generated by Django 5.0.2 on 2025-02-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0029_alter_entity_lemma_alter_entity_lemma_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="entities_done",
            field=models.BooleanField(default=False),
        ),
    ]
